### ISSUE TITLE
Review a599eb1 before tagging 0.4.3

### ISSUE THREAD

**Issue by giuseppeg** [suitcss/utils-text#18]
I accidentally pushed https://github.com/suitcss/utils-text/commit/a599eb1b3bfa1c3e8cc32abcb59fb39dab23fef1 to master, but it should be ok.
@necolas @timkelty @simonsmith shipit?

**Comment by necolas** [comment]
doesn't the original work in all browsers?

**Comment by giuseppeg** [comment]
The short answer is yes it does.
`overflow-wrap` is just the new standard name and `word-wrap` is an [alternate one](http://www.w3.org/TR/css3-text/#overflow-wrap-property).

I am ok with reverting the commit considering that was unintentional :)

**Comment by timkelty** [comment]
I'm fine with the change, since it seems `overflow-wrap` is to be the canonical version.

**Comment by giuseppeg** [comment]
Reverted, mainly because it was a nit and I didn't want to keep the [non-standard WebKit rule](https://code.google.com/p/chromium/issues/detail?id=492202).

**Comment by giuseppeg** [comment]
tagged [`0.4.3`](https://github.com/suitcss/utils-text/releases/tag/0.4.3)

**Comment by simonsmith** [comment]
On the back of this, @necolas do you mind adding us to publish `npm` packages too?

**Comment by necolas** [comment]
Sure. Please can you all confirm your npm user names here.

**Comment by simonsmith** [comment]
`simonsmith`

**Comment by giuseppeg** [comment]
`giuseppegurgone`

**Comment by timkelty** [comment]
`timkelty`
